services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.enable=true

      # HTTP redirect to HTTPS
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.yea.zenorahost.com`)"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.routers.portainer-http.middlewares=redirect-to-https"

      # HTTPS router
      - "traefik.http.routers.portainer-https.rule=Host(`portainer.yea.zenorahost.com`)"
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.tls.certresolver=namecheap"

      # Tell Traefik to connect to Portainer’s HTTP port (9000)
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      # Redirect middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

networks:
  frontend:
    external: true

volumes:
  portainer_data:
